import Foundation
import XCTest

final class ArchivePackagingScriptTests: XCTestCase {
    func testLocalArchiveVerifierEnforcesPromptPackageGates() throws {
        let scriptURL = projectURL("Scripts/verify_m10_local_archive.sh")
        let script = try String(contentsOf: scriptURL, encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(script.range(of: "xcodebuild archive"))
        XCTAssertNotNil(script.range(of: "M10_LOCAL_ARCHIVE_SNAPSHOT_ROOT"))
        XCTAssertNotNil(script.range(of: "prepare_snapshot"))
        XCTAssertNotNil(script.range(of: #"M10_LOCAL_ARCHIVE_SNAPSHOT_ROOT must be under /tmp"#))
        XCTAssertNotNil(script.range(of: #"M10_LOCAL_ARCHIVE_SNAPSHOT_ROOT must not point at the source checkout"#))
        XCTAssertNotNil(script.range(of: #"rsync -a "${source_root}/${entry}" "$target/""#))
        XCTAssertNotNil(script.range(of: #"-project "${work_root}/BuySellAI.xcodeproj""#))
        XCTAssertNotNil(script.range(of: "snapshot root: %s"))
        XCTAssertNotNil(script.range(of: "CODE_SIGNING_ALLOWED=NO"))
        XCTAssertNotNil(script.range(of: "CODE_SIGNING_REQUIRED=NO"))
        XCTAssertNotNil(script.range(of: "CODE_SIGN_IDENTITY=\"\""))
        XCTAssertNotNil(script.range(of: "MAX_APP_SIZE_KB:-20480"))
        XCTAssertNotNil(script.range(of: "PrivacyInfo.xcprivacy"))
        XCTAssertNotNil(script.range(of: "plutil -lint \"$privacy_manifest\""))
        XCTAssertNotNil(script.range(of: "AppIcon.appiconset/Contents.json"))
        XCTAssertNotNil(script.range(of: "AppIcon.appiconset/AppIcon-1024.png"))
        XCTAssertNotNil(script.range(of: "AppIcon60x60@2x.png"))
        XCTAssertNotNil(script.range(of: "AppIcon76x76@2x~ipad.png"))
        XCTAssertNotNil(script.range(of: "sips_property"))
        XCTAssertNotNil(script.range(of: "require_png_dimensions \"$app_icon_source\" 1024 1024 \"source App Store icon\""))
        XCTAssertNotNil(script.range(of: "require_png_dimensions \"$iphone_icon\" 120 120 \"archived iPhone app icon\""))
        XCTAssertNotNil(script.range(of: "require_png_dimensions \"$ipad_icon\" 152 152 \"archived iPad app icon\""))
        XCTAssertNotNil(script.range(of: "hasAlpha"))
        XCTAssertNotNil(script.range(of: "AppIcon asset catalog must declare a 1024x1024 iOS icon"))
        XCTAssertNotNil(script.range(of: "CFBundleIcons:CFBundlePrimaryIcon:CFBundleIconName"))
        XCTAssertNotNil(script.range(of: "CFBundleIcons~ipad:CFBundlePrimaryIcon:CFBundleIconName"))
        XCTAssertNotNil(script.range(of: "UIDesignRequiresCompatibility"))
        XCTAssertNotNil(script.range(of: "archived app must not request iOS design compatibility mode"))
        XCTAssertNotNil(script.range(of: "system design: current presentation, no UIDesignRequiresCompatibility"))
        XCTAssertNotNil(script.range(of: "require_privacy_manifest_values \"$privacy_manifest\""))
        XCTAssertNotNil(script.range(of: "privacy manifest must declare NSPrivacyTracking=false"))
        XCTAssertNotNil(script.range(of: "privacy manifest must declare exactly 4 collected data types"))
        XCTAssertNotNil(script.range(of: "NSPrivacyCollectedDataTypeEmailAddress"))
        XCTAssertNotNil(script.range(of: "NSPrivacyCollectedDataTypeUserID"))
        XCTAssertNotNil(script.range(of: "NSPrivacyCollectedDataTypePhotosorVideos"))
        XCTAssertNotNil(script.range(of: "NSPrivacyCollectedDataTypeOtherUserContent"))
        XCTAssertNotNil(script.range(of: "NSPrivacyCollectedDataTypePurposeAppFunctionality"))
        XCTAssertNotNil(script.range(of: "NSPrivacyAccessedAPICategoryUserDefaults"))
        XCTAssertNotNil(script.range(of: "CA92.1"))
        XCTAssertNotNil(script.range(of: "CFBundleIdentifier"))
        XCTAssertNotNil(script.range(of: "bundle id:"))
        XCTAssertNotNil(script.range(of: "CFBundleShortVersionString"))
        XCTAssertNotNil(script.range(of: "CFBundleVersion"))
        XCTAssertNotNil(script.range(of: "release build:"))
        XCTAssertNotNil(script.range(of: "app icon: AppIcon 1024x1024 source, 120x120 iPhone, 152x152 iPad"))
        XCTAssertNotNil(script.range(of: "system design: current presentation, no UIDesignRequiresCompatibility"))
        XCTAssertNotNil(script.range(of: "NSCameraUsageDescription"))
        XCTAssertNotNil(script.range(of: "ITSAppUsesNonExemptEncryption"))
        XCTAssertNotNil(script.range(of: "NSPhotoLibraryUsageDescription"))
        XCTAssertNotNil(script.range(of: "NSPhotoLibraryAddUsageDescription"))
    }

    func testAcceptanceDocsRouteNoSignArchiveThroughLocalVerifier() throws {
        let readme = try String(contentsOf: projectURL("README.md"), encoding: .utf8)
        let m10 = try String(contentsOf: projectURL("M10_ACCEPTANCE.md"), encoding: .utf8)

        XCTAssertNotNil(readme.range(of: "Scripts/verify_m10_local_archive.sh"))
        XCTAssertNotNil(readme.range(of: "M10_LOCAL_ARCHIVE_SNAPSHOT_ROOT=/tmp/buysell-m10-archive-worktree"))
        XCTAssertNotNil(m10.range(of: "Scripts/verify_m10_local_archive.sh"))
        XCTAssertNotNil(m10.range(of: "M10_LOCAL_ARCHIVE_SNAPSHOT_ROOT=/tmp/buysell-m10-archive-worktree"))
        XCTAssertNotNil(m10.range(of: "Binary-size check: archived app bundle stays under `20 MB`."))
        XCTAssertNotNil(m10.range(of: "App icon check: source App Store icon is a text-free camera-first 1024x1024 non-alpha PNG and the archive contains iPhone/iPad icon PNGs."))
        XCTAssertNotNil(m10.range(of: "Current-system design check: archived app omits `UIDesignRequiresCompatibility`."))
        XCTAssertNotNil(m10.range(of: "Privacy manifest content check"))
    }

    func testLatestDesignSDKVerifierRequiresLiquidGlassCapableToolchain() throws {
        let scriptURL = projectURL("Scripts/verify_m10_latest_design_sdk.sh")
        let script = try String(contentsOf: scriptURL, encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(script.range(of: "M10_MIN_LIQUID_GLASS_SDK_MAJOR:-27"))
        XCTAssertNotNil(script.range(of: "ALLOW_MISSING_LIQUID_GLASS_SDK"))
        XCTAssertNotNil(script.range(of: "xcodebuild -version"))
        XCTAssertNotNil(script.range(of: "xcrun --sdk iphoneos --show-sdk-version"))
        XCTAssertNotNil(script.range(of: "version_major"))
        XCTAssertNotNil(script.range(of: "NativeMaterialSurface.swift"))
        XCTAssertNotNil(script.range(of: "#if compiler(>=6.2)"))
        XCTAssertNotNil(script.range(of: "#available(iOS 26.0, *)"))
        XCTAssertNotNil(script.range(of: "glassEffect"))
        XCTAssertNotNil(script.range(of: "GlassEffectContainer"))
        XCTAssertNotNil(script.range(of: "GlassButtonStyle"))
        XCTAssertNotNil(script.range(of: "buttonStyle(.glass)"))
        XCTAssertNotNil(script.range(of: "buttonStyle(.glassProminent)"))
        XCTAssertNotNil(script.range(of: "nativeSystemSheetPresentationChrome"))
        XCTAssertNotNil(script.range(of: "NativeSystemSheetPresentationModifier"))
        XCTAssertNotNil(script.range(of: "fallbackPresentation"))
        XCTAssertNotNil(script.range(of: "Buttons.swift"))
        XCTAssertNotNil(script.range(of: "Chips.swift"))
        XCTAssertNotNil(script.range(of: "HomeView.swift"))
        XCTAssertNotNil(script.range(of: "CameraView.swift"))
        XCTAssertNotNil(script.range(of: "AuthView.swift"))
        XCTAssertNotNil(script.range(of: "SnapResultSheet.swift"))
        XCTAssertNotNil(script.range(of: "HowItWorksView.swift"))
        XCTAssertNotNil(script.range(of: "require_auth_marker"))
        XCTAssertNotNil(script.range(of: "NativeLiquidGlassControlGroupModifier"))
        XCTAssertNotNil(script.range(of: "nativeLiquidGlassControlGroup"))
        XCTAssertNotNil(script.range(of: "LiquidGlassSurfaceGroup(spacing: spacing)"))
        XCTAssertNotNil(script.range(of: "NativePrimaryButtonBackgroundModifier"))
        XCTAssertNotNil(script.range(of: "nativePrimaryButtonBackground"))
        XCTAssertNotNil(script.range(of: "content.background(Color.brand.primary, in: Capsule())"))
        XCTAssertNotNil(script.range(of: "NativeStandardButtonBackgroundModifier"))
        XCTAssertNotNil(script.range(of: "NativeRoundedButtonBackgroundModifier"))
        XCTAssertNotNil(script.range(of: "NativeIconButtonBackgroundModifier"))
        XCTAssertNotNil(script.range(of: "nativeStandardButtonBackground"))
        XCTAssertNotNil(script.range(of: "nativeRoundedButtonBackground"))
        XCTAssertNotNil(script.range(of: "nativeIconButtonBackground"))
        XCTAssertNotNil(script.range(of: ".nativePrimaryButtonBackground()"))
        XCTAssertNotNil(script.range(of: ".tint(Color.brand.primary)"))
        XCTAssertNotNil(script.range(of: ".nativeStandardButtonBackground(tintOpacity: 0.7, strokeOpacity: 0.64)"))
        XCTAssertNotNil(script.range(of: ".nativeStandardButtonBackground(tintOpacity: 0.64, strokeOpacity: 0.84)"))
        XCTAssertNotNil(script.range(of: "SnapActionRow()"))
        XCTAssertNotNil(script.range(of: #".navigationTitle("BuySell.".localized)"#))
        XCTAssertNotNil(script.range(of: "BrandWordmark(size: .regular)"))
        XCTAssertNotNil(script.range(of: ".nativeLiquidGlassControlGroup(spacing: Spacing.md)"))
        XCTAssertNotNil(script.range(of: "CameraPreview(session: controller.session) { tap in"))
        XCTAssertNotNil(script.range(of: "handleFocusTap(tap)"))
        XCTAssertNotNil(script.range(of: "CameraFocusRing()"))
        XCTAssertNotNil(script.range(of: #"systemImage: "arrow.triangle.2.circlepath.camera""#))
        XCTAssertNotNil(script.range(of: "cameraCapabilities.canSwitchCamera"))
        XCTAssertNotNil(script.range(of: "handleScenePhase"))
        XCTAssertNotNil(script.range(of: "pauseCameraForScenePhase"))
        XCTAssertNotNil(script.range(of: "restartCameraAfterInterruption"))
        XCTAssertNotNil(script.range(of: "NavigationLink(value: AuthRoute.email)"))
        XCTAssertNotNil(script.range(of: ".buttonStyle(.borderedProminent)"))
        XCTAssertNotNil(script.range(of: ".background(.bar)"))
        XCTAssertNotNil(script.range(of: ".nativeIconButtonBackground("))
        XCTAssertNotNil(script.range(of: ".nativeRoundedButtonBackground("))
        XCTAssertNotNil(script.range(of: "private func categoryMenuItemIcon(for category: Category) -> String"))
        XCTAssertNotNil(script.range(of: "private func conditionMenuItemIcon(for condition: Condition) -> String"))
        XCTAssertNotNil(script.range(of: #"Image(systemName: isSelected ? "checkmark.circle.fill" : systemImage)"#))
        XCTAssertNotNil(script.range(of: "UIDesignRequiresCompatibility"))
        XCTAssertNotNil(script.range(of: "M10 latest design SDK pending"))
        XCTAssertNotNil(script.range(of: "M10 latest design SDK passed"))
        XCTAssertNotNil(script.range(of: "source liquid glass: compiler-gated glassEffect, GlassEffectContainer, GlassButtonStyle, .glass, .glassProminent"))
        XCTAssertNotNil(script.range(of: "primary button glass: iOS 26+ prominent glass with orange tint, capsule fallback"))
        XCTAssertNotNil(script.range(of: "standard button glass: iOS 26+ standard glass with material fallbacks for secondary, ghost, chip, icon, and remaining custom controls"))
        XCTAssertNotNil(script.range(of: "home setup: native inset grouped task list with branded toolbar wordmark, account, and settings actions"))
        XCTAssertNotNil(script.range(of: "camera setup: native top controls, tap focus, camera switching, scene-phase recovery, and capture controls preserve compiler-gated GlassEffectContainer on iOS 26+"))
        XCTAssertNotNil(script.range(of: "auth setup: native inset grouped list, NavigationLink email push, and system bottom bars"))
        XCTAssertNotNil(script.range(of: "tutorial setup: native inset grouped guide with a system bottom bar"))
        XCTAssertNotNil(script.range(of: "menu item icons: category and condition menus use SF Symbols with selected checkmarks"))
        XCTAssertNotNil(script.range(of: "system sheet background: iOS 26+ native Liquid Glass, regularMaterial fallback"))
        XCTAssertNotNil(script.range(of: "system design: current presentation, no UIDesignRequiresCompatibility"))
    }

    private func projectURL(_ path: String) -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent(path)
    }
}
