import Foundation
import XCTest

final class M10AppStoreMetadataScriptTests: XCTestCase {
    func testMetadataVerifierRequiresConcreteAppStoreConnectSubmissionFields() throws {
        let scriptURL = projectURL("Scripts/verify_m10_app_store_metadata.sh")
        let script = try String(contentsOf: scriptURL, encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(script.range(of: "ALLOW_PENDING_METADATA"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_METADATA"))
        XCTAssertNotNil(script.range(of: "App name"))
        XCTAssertNotNil(script.range(of: "Bundle ID"))
        XCTAssertNotNil(script.range(of: "SKU"))
        XCTAssertNotNil(script.range(of: "Primary category"))
        XCTAssertNotNil(script.range(of: "Age rating"))
        XCTAssertNotNil(script.range(of: "DSA trader status"))
        XCTAssertNotNil(script.range(of: "Account owner legal confirmation"))
        XCTAssertNotNil(script.range(of: "Support URL"))
        XCTAssertNotNil(script.range(of: "Privacy Policy URL"))
        XCTAssertNotNil(script.range(of: "Screenshots"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_IPHONE_SCREENSHOT_DIR"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_IPHONE_SCREENSHOT_WIDTH"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_IPHONE_SCREENSHOT_HEIGHT"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_IPAD_SCREENSHOT_DIR"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_IPAD_SCREENSHOT_WIDTH:-2064"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_IPAD_SCREENSHOT_HEIGHT:-2752"))
        XCTAssertNotNil(script.range(of: "required_screenshots"))
        XCTAssertNotNil(script.range(of: "01-home.png"))
        XCTAssertNotNil(script.range(of: "02-result.png"))
        XCTAssertNotNil(script.range(of: "03-marketplaces.png"))
        XCTAssertNotNil(script.range(of: "04-listing.png"))
        XCTAssertNotNil(script.range(of: "require_screenshot_assets"))
        XCTAssertNotNil(script.range(of: "require_screenshot_visual_quality"))
        XCTAssertNotNil(script.range(of: "require_screenshot_capture_result"))
        XCTAssertNotNil(script.range(of: "iPhone 6.9 result bundle"))
        XCTAssertNotNil(script.range(of: "iPad 13 result bundle"))
        XCTAssertNotNil(script.range(of: "BuySellAIUITests/testM10AppStoreScreenshotsCanBeCaptured()"))
        XCTAssertNotNil(script.range(of: "xcrun xcresulttool get test-results tests"))
        XCTAssertNotNil(script.range(of: "sips -g pixelWidth"))
        XCTAssertNotNil(script.range(of: "sips -g pixelHeight"))
        XCTAssertNotNil(script.range(of: "expected ${expected_width}x${expected_height}"))
        XCTAssertNotNil(script.range(of: "blank or nearly blank screenshot"))
        XCTAssertNotNil(script.range(of: "dark horizontal artifact detected"))
        XCTAssertNotNil(script.range(of: "warm orange brand signal is missing"))
        XCTAssertNotNil(script.range(of: "failed visual quality check"))
        XCTAssertNotNil(script.range(of: #"require_terms "Screenshots" "screenshot evidence" "screenshot" "iphone" "ipad""#))
        XCTAssertNotNil(script.range(of: "metadata 'Screenshots' must reference $label screenshot file"))
        XCTAssertNotNil(script.range(of: "screenshot capture test did not pass"))
        XCTAssertNotNil(script.range(of: "App Review notes"))
        XCTAssertNotNil(script.range(of: "Export compliance"))
        XCTAssertNotNil(script.range(of: "Accessibility labels"))
        XCTAssertNotNil(script.range(of: "Accessibility URL"))
        XCTAssertNotNil(script.range(of: "Accessibility common tasks"))
        XCTAssertNotNil(script.range(of: "Accessibility evidence"))
        XCTAssertNotNil(script.range(of: #"require_public_https_url "Accessibility URL""#))
        XCTAssertNotNil(script.range(of: #"require_terms "Accessibility URL" "dedicated accessibility page URL" "accessibility""#))
        XCTAssertNotNil(script.range(of: #"require_terms "Accessibility labels" "Accessibility Nutrition Labels" "iphone" "ipad""#))
        XCTAssertNotNil(script.range(of: #"require_absent_terms "Accessibility labels" "unsupported accessibility labels" "voice control""#))
        XCTAssertNotNil(script.range(of: "must not claim $label without recorded evidence"))
        XCTAssertNotNil(script.range(of: #"require_terms "Accessibility common tasks" "common tasks""#))
        XCTAssertNotNil(script.range(of: #"require_terms "Accessibility evidence" "accessibility evidence""#))
        XCTAssertNotNil(script.range(of: #""bold text" "reduce transparency""#))
        XCTAssertNotNil(script.range(of: "unconfirmed_metadata_markers"))
        XCTAssertNotNil(script.range(of: "require_no_unconfirmed_assumption"))
        XCTAssertNotNil(script.range(of: #""pass"|"passed"|"tested"|"verified""#))
        XCTAssertNotNil(script.range(of: #"s/[[:punct:]]+/ /g"#))
        XCTAssertNotNil(script.range(of: "assumption"))
        XCTAssertNotNil(script.range(of: "before final submission"))
        XCTAssertNotNil(script.range(of: "not confirmed"))
        XCTAssertNotNil(script.range(of: "confirm in app store connect"))
        XCTAssertNotNil(script.range(of: "still contains unconfirmed account-owner/legal wording"))
        XCTAssertNotNil(script.range(of: "metadata '$field' is not recorded"))
        XCTAssertNotNil(script.range(of: "metadata '$field' must be a full https URL"))
        XCTAssertNotNil(script.range(of: "require_public_https_url \"Support URL\""))
        XCTAssertNotNil(script.range(of: "require_public_https_url \"Privacy Policy URL\""))
        XCTAssertNotNil(script.range(of: #"curl -L -sS -o /dev/null -w "%{http_code}""#))
        XCTAssertNotNil(script.range(of: "publicly reachable without authentication"))
        XCTAssertNotNil(script.range(of: "HTTP $status"))
        XCTAssertNotNil(script.range(of: "expected <= ${max_bytes}"))
        XCTAssertNotNil(script.range(of: "print_evidence_markers()"))
        XCTAssertGreaterThanOrEqual(script.components(separatedBy: "print_evidence_markers").count - 1, 3)
        XCTAssertNotNil(script.range(of: "Recorded App Store metadata evidence markers:"))
        XCTAssertNotNil(script.range(of: "screenshot directory: %s"))
        XCTAssertNotNil(script.range(of: "legal: %s"))
        XCTAssertNotNil(script.range(of: "screenshot files: %s"))
        XCTAssertNotNil(script.range(of: "screenshot sets: iPhone 6.9, iPad 13"))
        XCTAssertNotNil(script.range(of: "screenshot dimensions: iPhone 6.9 %sx%s; iPad 13 %sx%s"))
        XCTAssertNotNil(script.range(of: "iphone 6.9 screenshot directory: %s"))
        XCTAssertNotNil(script.range(of: "ipad 13 screenshot directory: %s"))
        XCTAssertNotNil(script.range(of: "screenshot quality: no blank or dark-strip artifacts"))
        XCTAssertNotNil(script.range(of: "screenshot brand signal: warm orange present"))
        XCTAssertNotNil(script.range(of: "screenshot result bundle: %s"))
        XCTAssertNotNil(script.range(of: "iphone 6.9 screenshot result bundle: %s"))
        XCTAssertNotNil(script.range(of: "ipad 13 screenshot result bundle: %s"))
        XCTAssertNotNil(script.range(of: "screenshot capture test: %s"))
        XCTAssertNotNil(script.range(of: "accessibility url: %s"))
        XCTAssertNotNil(script.range(of: "accessibility labels: %s"))
        XCTAssertNotNil(script.range(of: "accessibility evidence: %s"))
        XCTAssertNotNil(script.range(of: "M10 App Store metadata evidence passed"))
    }

    func testMetadataVerifierRequiresPrivacyAnswersToMatchManifestScope() throws {
        let script = try String(contentsOf: projectURL("Scripts/verify_m10_app_store_metadata.sh"), encoding: .utf8)

        XCTAssertNotNil(script.range(of: "App privacy data types"))
        XCTAssertNotNil(script.range(of: "email address"))
        XCTAssertNotNil(script.range(of: "user id"))
        XCTAssertNotNil(script.range(of: "photos or videos"))
        XCTAssertNotNil(script.range(of: "other user content"))
        XCTAssertNotNil(script.range(of: #"require_exact "Data linked to user" "Yes""#))
        XCTAssertNotNil(script.range(of: #"require_exact "Data used for tracking" "No""#))
        XCTAssertNotNil(script.range(of: #"require_exact "Tracking domains" "None""#))
        XCTAssertNotNil(script.range(of: #"require_exact "Data use purpose" "App Functionality""#))
        XCTAssertNotNil(script.range(of: "delete account"))
        XCTAssertNotNil(script.range(of: "itsappusesnonexemptencryption=false"))
        XCTAssertNotNil(script.range(of: "https"))
    }

    func testMetadataScreenshotQualityCheckStreamsRowsForFastM10Runs() throws {
        let script = try String(contentsOf: projectURL("Scripts/verify_m10_app_store_metadata.sh"), encoding: .utf8)

        XCTAssertNil(
            script.range(of: "rows = []"),
            "Screenshot validation should not retain every decoded row before computing quality metrics."
        )
        XCTAssertNotNil(script.range(of: "content_threshold = 245 * 10000"))
        XCTAssertNotNil(script.range(of: "dark_threshold = 24 * 10000"))
        XCTAssertNotNil(script.range(of: "brand_orange_threshold = 0.002"))
        XCTAssertNotNil(script.range(of: "M10_SCREENSHOT_QUALITY_MAX_EDGE:-420"))
        XCTAssertNotNil(script.range(of: "sips -Z"))
        XCTAssertNotNil(script.range(of: "buysell-screenshot-quality"))
        XCTAssertNotNil(script.range(of: "brand_orange_pixels += 1"))
        XCTAssertNotNil(script.range(of: "red > blue + 50"))
        XCTAssertNotNil(script.range(of: "average_luminance = luminance_total / (pixel_count * 10000)"))
        XCTAssertNotNil(script.range(of: "previous = row"))
    }

    func testMetadataVerifierTreatsUnconfirmedLegalAnswersAsPending() throws {
        let script = try String(contentsOf: projectURL("Scripts/verify_m10_app_store_metadata.sh"), encoding: .utf8)
        let metadata = try String(contentsOf: projectURL("M10_APP_STORE_METADATA.md"), encoding: .utf8)
        let readme = try String(contentsOf: projectURL("README.md"), encoding: .utf8)

        XCTAssertNotNil(script.range(of: #"require_no_unconfirmed_assumption "Age rating""#))
        XCTAssertNotNil(script.range(of: #"require_no_unconfirmed_assumption "DSA trader status""#))
        XCTAssertNotNil(script.range(of: #"require_no_unconfirmed_assumption "Account owner legal confirmation""#))
        XCTAssertNotNil(script.range(of: #"require_no_unconfirmed_assumption "Copyright""#))
        XCTAssertNotNil(script.range(of: #"require_no_unconfirmed_assumption "Export compliance""#))
        XCTAssertNotNil(script.range(of: #"require_terms "Account owner legal confirmation" "account-owner legal confirmation""#))
        XCTAssertNotNil(metadata.range(of: "Account owner legal confirmation"))
        XCTAssertNotNil(metadata.range(of: "Pending - App Store Connect account owner must confirm"))
        XCTAssertNotNil(metadata.range(of: "DSA trader status"))
        XCTAssertNotNil(metadata.range(of: "copyright"))
        XCTAssertNotNil(metadata.range(of: "age rating"))
        XCTAssertNotNil(metadata.range(of: "export compliance"))
        XCTAssertNotNil(readme.range(of: "verifier intentionally keeps metadata pending"))
    }

    func testMetadataTemplateAndDocsRouteThroughVerifier() throws {
        let metadataURL = projectURL("M10_APP_STORE_METADATA.md")
        let metadata = try String(contentsOf: metadataURL, encoding: .utf8)
        let screenshotReadme = try String(contentsOf: projectURL("AppStoreAssets/Screenshots/README.md"), encoding: .utf8)
        let readme = try String(contentsOf: projectURL("README.md"), encoding: .utf8)
        let m10 = try String(contentsOf: projectURL("M10_ACCEPTANCE.md"), encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: metadataURL.path))
        XCTAssertNotNil(metadata.range(of: "App Store Connect metadata"))
        XCTAssertNotNil(metadata.range(of: "App privacy data types"))
        XCTAssertNotNil(metadata.range(of: "Accessibility Nutrition Labels"))
        XCTAssertNotNil(metadata.range(of: "https://buysell-ai-support.o5hinwavve.chatgpt.site/accessibility"))
        XCTAssertNotNil(metadata.range(of: "VoiceOver"))
        XCTAssertNotNil(metadata.range(of: "Larger Text"))
        XCTAssertNotNil(metadata.range(of: "Reduced Motion"))
        XCTAssertNotNil(metadata.range(of: "Bold Text"))
        XCTAssertNotNil(metadata.range(of: "Reduce Transparency"))
        XCTAssertNotNil(metadata.range(of: "Voice Control is intentionally excluded"))
        XCTAssertNotNil(metadata.range(of: "Account owner legal confirmation"))
        XCTAssertNotNil(metadata.range(of: "Email Address, User ID, Photos or Videos, Other User Content"))
        XCTAssertNotNil(metadata.range(of: "ALLOW_PENDING_METADATA=1"))
        XCTAssertNotNil(metadata.range(of: "/tmp/buysell-submit-readiness-full.xcresult"))
        XCTAssertNotNil(metadata.range(of: "AppStoreAssets/Screenshots/iPhone-16-Pro-Max/"))
        XCTAssertNotNil(metadata.range(of: "AppStoreAssets/Screenshots/iPad-Pro-13-inch-M4/"))
        XCTAssertNotNil(metadata.range(of: "/tmp/buysell-m10-screenshots-iphone-16-pro-max.xcresult"))
        XCTAssertNotNil(metadata.range(of: "/tmp/buysell-m10-screenshots-ipad-pro-13.xcresult"))
        XCTAssertNotNil(screenshotReadme.range(of: "/tmp/buysell-submit-readiness-full.xcresult"))
        XCTAssertNotNil(screenshotReadme.range(of: "iPhone 16 Pro Max"))
        XCTAssertNotNil(screenshotReadme.range(of: "iPad Pro 13-inch"))
        XCTAssertNotNil(screenshotReadme.range(of: "bash Scripts/verify_m10_app_store_metadata.sh M10_APP_STORE_METADATA.md"))
        XCTAssertNotNil(readme.range(of: "screenshot directory:"))
        XCTAssertNotNil(readme.range(of: "screenshot dimensions:"))
        XCTAssertNotNil(readme.range(of: "screenshot brand signal:"))
        XCTAssertNotNil(readme.range(of: "legal:"))
        XCTAssertNotNil(readme.range(of: "accessibility url:"))
        XCTAssertNotNil(readme.range(of: "accessibility labels:"))
        XCTAssertNotNil(readme.range(of: "accessibility evidence:"))
        XCTAssertNotNil(m10.range(of: "/tmp/buysell-submit-readiness-full.xcresult"))
        XCTAssertNotNil(m10.range(of: "screenshot directory:"))
        XCTAssertNotNil(m10.range(of: "screenshot dimensions:"))
        XCTAssertNotNil(m10.range(of: "screenshot brand signal:"))
        XCTAssertNotNil(m10.range(of: "legal:"))
        XCTAssertNotNil(m10.range(of: "accessibility url:"))
        XCTAssertNotNil(m10.range(of: "accessibility labels:"))
        XCTAssertNotNil(m10.range(of: "accessibility evidence:"))
        XCTAssertNotNil(readme.range(of: "Scripts/verify_m10_app_store_metadata.sh M10_APP_STORE_METADATA.md"))
        XCTAssertNotNil(readme.range(of: "/tmp/buysell-submit-readiness-app-store-metadata.log"))
        XCTAssertNotNil(m10.range(of: "Scripts/verify_m10_app_store_metadata.sh M10_APP_STORE_METADATA.md"))
        XCTAssertNotNil(m10.range(of: "Complete App Store Connect metadata"))
        XCTAssertNotNil(m10.range(of: "/tmp/buysell-submit-readiness-app-store-metadata.log"))
    }

    func testTodayFeatureNominationPackageRoutesThroughVerifier() throws {
        let nominationURL = projectURL("M10_TODAY_FEATURE_NOMINATION.md")
        let scriptURL = projectURL("Scripts/verify_m10_today_feature_nomination.sh")
        let nomination = try String(contentsOf: nominationURL, encoding: .utf8)
        let script = try String(contentsOf: scriptURL, encoding: .utf8)
        let readme = try String(contentsOf: projectURL("README.md"), encoding: .utf8)
        let m10 = try String(contentsOf: projectURL("M10_ACCEPTANCE.md"), encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: nominationURL.path))
        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(nomination.range(of: "Apple Today Feature Nomination Package"))
        XCTAssertNotNil(nomination.range(of: "Featuring Nominations in App Store Connect"))
        XCTAssertNotNil(nomination.range(of: "https://developer.apple.com/app-store/getting-featured/"))
        XCTAssertNotNil(nomination.range(of: "https://developer.apple.com/help/app-store-connect/manage-featuring-nominations/nominate-your-app-for-featuring/"))
        XCTAssertNotNil(nomination.range(of: "Submit at least two weeks"))
        XCTAssertNotNil(nomination.range(of: "up to three months"))
        XCTAssertNotNil(nomination.range(of: "Today tab and Apps tab editorial consideration"))
        XCTAssertNotNil(nomination.range(of: "Sell anything in three taps"))
        XCTAssertNotNil(nomination.range(of: "SwiftUI"))
        XCTAssertNotNil(nomination.range(of: "AVFoundation"))
        XCTAssertNotNil(nomination.range(of: "SwiftData"))
        XCTAssertNotNil(nomination.range(of: "VoiceOver"))
        XCTAssertNotNil(nomination.range(of: "no tracking domains"))
        XCTAssertNotNil(nomination.range(of: "AppStoreAssets/Screenshots/iPhone-16-Pro-Max/"))
        XCTAssertNotNil(nomination.range(of: "AppStoreAssets/Screenshots/iPad-Pro-13-inch-M4/"))
        XCTAssertNotNil(nomination.range(of: "AppIcon-1024.png"))

        XCTAssertNotNil(script.range(of: "M10_TODAY_FEATURE_NOMINATION"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_METADATA"))
        XCTAssertNotNil(script.range(of: "Required App Store Connect role"))
        XCTAssertNotNil(script.range(of: "Preferred placement"))
        XCTAssertNotNil(script.range(of: "Submission lead time"))
        XCTAssertNotNil(script.range(of: #"require_terms "Preferred placement" "today tab" "apps tab""#))
        XCTAssertNotNil(script.range(of: #"require_terms "Submission lead time" "two weeks" "three months""#))
        XCTAssertNotNil(script.range(of: #"require_terms "New content/functionality" "avfoundation" "supabase" "marketplace" "sign in with apple" "swiftdata""#))
        XCTAssertNotNil(script.range(of: #"require_terms "Technology quality" "swiftui" "observation" "avfoundation" "swiftdata" "async/await""#))
        XCTAssertNotNil(script.range(of: #"require_terms "Accessibility story" "voiceover" "larger text" "reduced motion" "reduce transparency" "44-point""#))
        XCTAssertNotNil(script.range(of: #"require_file "BuySellAI/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png""#))
        XCTAssertNotNil(script.range(of: "M10 Today feature nomination package passed"))
        XCTAssertNotNil(script.range(of: "assets: screenshots iPhone 6.9, iPad 13, text-free 1024 icon"))

        XCTAssertNotNil(readme.range(of: "Scripts/verify_m10_today_feature_nomination.sh M10_TODAY_FEATURE_NOMINATION.md"))
        XCTAssertNotNil(readme.range(of: "/tmp/buysell-submit-readiness-today-feature.log"))
        XCTAssertNotNil(m10.range(of: "Apple Today feature nomination evidence"))
        XCTAssertNotNil(m10.range(of: "M10_TODAY_FEATURE_NOMINATION.md"))
        XCTAssertNotNil(m10.range(of: "M10 Today feature nomination package passed"))
    }

    func testAppStoreScreenshotCaptureResetsVisualPreferences() throws {
        let uiTests = try String(contentsOf: projectURL("BuySellAIUITests/BuySellAIUITests.swift"), encoding: .utf8)
        let testRange = try XCTUnwrap(uiTests.range(of: "func testM10AppStoreScreenshotsCanBeCaptured() throws"))
        let helperRange = try XCTUnwrap(uiTests.range(of: "private func appStoreScreenshotDirectory()", range: testRange.upperBound..<uiTests.endIndex))
        let testSource = String(uiTests[testRange.lowerBound..<helperRange.lowerBound])

        XCTAssertNotNil(
            testSource.range(of: "--reset-preferences"),
            "App Store screenshot capture must reset visual preferences for deterministic assets."
        )
        XCTAssertNotNil(testSource.range(of: "--reset-auth"))
        XCTAssertNotNil(testSource.range(of: "--reset-history"))
    }

    func testAppStoreScreenshotCaptureUsesSimulatorDeviceFolders() throws {
        let uiTests = try String(contentsOf: projectURL("BuySellAIUITests/BuySellAIUITests.swift"), encoding: .utf8)
        let helperRange = try XCTUnwrap(uiTests.range(of: "private func appStoreScreenshotDirectory()"))
        let nextHelperRange = try XCTUnwrap(uiTests.range(of: "private func tapMarketplace(", range: helperRange.upperBound..<uiTests.endIndex))
        let helperSource = String(uiTests[helperRange.lowerBound..<nextHelperRange.lowerBound])

        XCTAssertNotNil(helperSource.range(of: "M10_SCREENSHOT_DIR"))
        XCTAssertNotNil(helperSource.range(of: "SIMULATOR_DEVICE_NAME"))
        XCTAssertNotNil(helperSource.range(of: "appStoreScreenshotDeviceFolder()"))
        XCTAssertNotNil(helperSource.range(of: #"^Clone \d+ of "#))
        XCTAssertNotNil(helperSource.range(of: ".regularExpression"))
        XCTAssertNotNil(helperSource.range(of: #"replacingOccurrences(of: " ", with: "-")"#))
    }

    func testAppStoreScreenshotCaptureRefreshesStoredAssets() throws {
        let uiTests = try String(contentsOf: projectURL("BuySellAIUITests/BuySellAIUITests.swift"), encoding: .utf8)
        let helperRange = try XCTUnwrap(uiTests.range(of: "private func saveAppStoreScreenshot("))
        let nextHelperRange = try XCTUnwrap(uiTests.range(of: "private func assertSettingsState(", range: helperRange.upperBound..<uiTests.endIndex))
        let helperSource = String(uiTests[helperRange.lowerBound..<nextHelperRange.lowerBound])

        XCTAssertNotNil(
            helperSource.range(of: "try screenshot.pngRepresentation.write(to: destination, options: .atomic)"),
            "App Store screenshot capture must write refreshed PNG files."
        )
        XCTAssertNil(
            helperSource.range(of: "fileExists(atPath: destination.path)"),
            "App Store screenshot capture must not keep stale existing PNG files."
        )
    }

    func testCombinedSubmitReadinessRequiresMetadataEvidenceLog() throws {
        let script = try String(contentsOf: projectURL("Scripts/verify_m10_submit_readiness.sh"), encoding: .utf8)

        XCTAssertNotNil(script.range(of: "M10_APP_STORE_METADATA"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_METADATA_LOG"))
        XCTAssertNotNil(script.range(of: "/tmp/buysell-submit-readiness-app-store-metadata.log"))
        XCTAssertNotNil(script.range(of: "M10 App Store metadata evidence passed"))
        XCTAssertNotNil(script.range(of: "App Store metadata evidence log"))
        XCTAssertNotNil(script.range(of: "screenshot files: 8"))
        XCTAssertNotNil(script.range(of: "screenshot dimensions: iPhone 6.9 1320x2868; iPad 13 2064x2752"))
        XCTAssertNotNil(script.range(of: "iphone 6.9 screenshot directory: AppStoreAssets/Screenshots/iPhone-16-Pro-Max"))
        XCTAssertNotNil(script.range(of: "ipad 13 screenshot directory: AppStoreAssets/Screenshots/iPad-Pro-13-inch-M4"))
        XCTAssertNotNil(script.range(of: "screenshot quality: no blank or dark-strip artifacts"))
        XCTAssertNotNil(script.range(of: "screenshot brand signal: warm orange present"))
        XCTAssertNotNil(script.range(of: "iphone 6.9 screenshot result bundle: /tmp/buysell-m10-screenshots-iphone-16-pro-max.xcresult"))
        XCTAssertNotNil(script.range(of: "ipad 13 screenshot result bundle: /tmp/buysell-m10-screenshots-ipad-pro-13.xcresult"))
        XCTAssertNotNil(script.range(of: "legal:"))
        XCTAssertNotNil(script.range(of: "accessibility url:"))
        XCTAssertNotNil(script.range(of: "accessibility labels:"))
        XCTAssertNotNil(script.range(of: "accessibility evidence:"))
        XCTAssertNotNil(script.range(of: "screenshot result bundle:"))
        XCTAssertNotNil(script.range(of: "screenshot capture test: BuySellAIUITests/testM10AppStoreScreenshotsCanBeCaptured()"))
        XCTAssertNotNil(script.range(of: "M10AppStoreMetadataScriptTests/testMetadataVerifierRequiresConcreteAppStoreConnectSubmissionFields"))
        XCTAssertNotNil(script.range(of: "App Store metadata evidence is incomplete"))
    }

    private func projectURL(_ path: String) -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent(path)
    }
}
