import Foundation
import XCTest

final class M10BackendPreflightScriptTests: XCTestCase {
    func testBackendPreflightScriptValidatesConfigAndCallsRequiredSupabaseRoutes() throws {
        let scriptURL = projectURL("Scripts/preflight_m10_backend.sh")
        let script = try String(contentsOf: scriptURL, encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(script.range(of: "ALLOW_MISSING_BACKEND"))
        XCTAssertNotNil(script.range(of: "BuySellAI/App/Config.plist"))
        XCTAssertNotNil(script.range(of: "SUPABASE_URL"))
        XCTAssertNotNil(script.range(of: "SUPABASE_ANON_KEY"))
        XCTAssertNotNil(script.range(of: "SUPABASE_URL still contains the Config.plist.example placeholder"))
        XCTAssertNotNil(script.range(of: "SUPABASE_ANON_KEY still contains the Config.plist.example placeholder"))
        XCTAssertNotNil(script.range(of: #"AQ\.[0-9A-Za-z_-]{20,}"#))
        XCTAssertNotNil(script.range(of: #"AIza[0-9A-Za-z_-]{20,}"#))
        XCTAssertNotNil(script.range(of: #"sk-[0-9A-Za-z_-]{20,}"#))
        XCTAssertNotNil(script.range(of: "M10_ANALYZE_IMAGE_JPEG"))
        XCTAssertNotNil(script.range(of: "M10_ANALYZE_IMAGE_DATA_URL"))
        XCTAssertNotNil(script.range(of: "data:image/jpeg;base64,"))
        XCTAssertNotNil(script.range(of: "curl -sS --show-error --max-time"))
        XCTAssertNotNil(script.range(of: "analyze-image"))
        XCTAssertNotNil(script.range(of: "generate-listing"))
        XCTAssertNotNil(script.range(of: "call_rejected_function"))
        XCTAssertNotNil(script.range(of: "accepted invalid payload; expected HTTP"))
        XCTAssertNotNil(script.range(of: "invalid-analyze-missing-image-payload.json"))
        XCTAssertNotNil(script.range(of: "invalid-analyze-png-payload.json"))
        XCTAssertNotNil(script.range(of: "invalid-analyze-base64-payload.json"))
        XCTAssertNotNil(script.range(of: "invalid-analyze-jpeg-bytes-payload.json"))
        XCTAssertNotNil(script.range(of: #"imageDataUrl": "data:image/png;base64,AQID""#))
        XCTAssertNotNil(script.range(of: #"imageDataUrl": "data:image/jpeg;base64,not-base64""#))
        XCTAssertNotNil(script.range(of: #"imageDataUrl": "data:image/jpeg;base64,AQID""#))
        XCTAssertNotNil(script.range(of: "analyze-image non-JPEG bytes"))
        XCTAssertNotNil(script.range(of: "invalid-listing-platform-payload.json"))
        XCTAssertNotNil(script.range(of: "invalid-listing-category-payload.json"))
        XCTAssertNotNil(script.range(of: "invalid-listing-condition-payload.json"))
        XCTAssertNotNil(script.range(of: #"platform": "garage-sale""#))
        XCTAssertNotNil(script.range(of: #"category": "Pets""#))
        XCTAssertNotNil(script.range(of: #"condition": "broken""#))
        XCTAssertNotNil(script.range(of: "store-apple-token"))
        XCTAssertNotNil(script.range(of: "delete-account"))
        XCTAssertNotNil(script.range(of: "probe_protected_function"))
        XCTAssertNotNil(script.range(of: "probe_protected_table"))
        XCTAssertNotNil(script.range(of: "accepted an anonymous request; expected JWT protection"))
        XCTAssertNotNil(script.range(of: "protected endpoint is not deployed"))
        XCTAssertNotNil(script.range(of: "accepted an anonymous read; expected RLS/grant protection"))
        XCTAssertNotNil(script.range(of: "protected table is not deployed"))
        XCTAssertNotNil(script.range(of: "expected 401 or 403"))
        XCTAssertNotNil(script.range(of: #"rest_base="${supabase_url}/rest/v1""#))
        XCTAssertNotNil(script.range(of: "history?select=id&limit=1"))
        XCTAssertNotNil(script.range(of: "apple_auth_tokens?select=user_id&limit=1"))
        XCTAssertNotNil(script.range(of: "validate_analyze_response"))
        XCTAssertNotNil(script.range(of: "validate_listing_response"))
        XCTAssertNotNil(script.range(of: "currentPrice must be greater than zero"))
        XCTAssertNotNil(script.range(of: "listing contains markdown fences"))
        XCTAssertNotNil(script.range(of: "listing contains a generated preamble"))
        XCTAssertNotNil(script.range(of: "listing is missing TITLE"))
        XCTAssertNotNil(script.range(of: "listing is missing DESCRIPTION"))
        XCTAssertNotNil(script.range(of: "listing has empty TITLE"))
        XCTAssertNotNil(script.range(of: "listing has empty DESCRIPTION"))
        XCTAssertNotNil(script.range(of: "title_match = re.search"))
        XCTAssertNotNil(script.range(of: "description_match = re.search"))
        XCTAssertNotNil(script.range(of: "title_body ="))
        XCTAssertNotNil(script.range(of: "description_body ="))
        XCTAssertNotNil(script.range(of: "M10 backend preflight passed"))
        XCTAssertNotNil(script.range(of: "schema: history apple_auth_tokens"))
        XCTAssertNotNil(script.range(of: "functions: analyze-image generate-listing store-apple-token delete-account"))
        XCTAssertNotNil(script.range(of: "protected functions: store-apple-token delete-account"))
        XCTAssertNotNil(script.range(of: "protected tables: history apple_auth_tokens"))
        XCTAssertNotNil(script.range(of: "analyze item:"))
        XCTAssertNotNil(script.range(of: "analyze rejection contract: missing jpeg base64"))
        XCTAssertNotNil(script.range(of: "listing contract: title-description-plain-text"))
        XCTAssertNotNil(script.range(of: "listing rejection contract: platform category condition"))
        XCTAssertNotNil(script.range(of: "listing bytes:"))
        XCTAssertNil(script.range(of: "printf 'SUPABASE_ANON_KEY"))
    }

    func testBackendPreflightPendingModeDocumentsMissingExternalState() throws {
        let script = try String(contentsOf: projectURL("Scripts/preflight_m10_backend.sh"), encoding: .utf8)

        XCTAssertNotNil(script.range(of: "M10 backend preflight pending"))
        XCTAssertNotNil(script.range(of: "Config.plist is missing"))
        XCTAssertNotNil(script.range(of: "Config.plist.example placeholder"))
        XCTAssertNotNil(script.range(of: "M10_ANALYZE_IMAGE_JPEG or M10_ANALYZE_IMAGE_DATA_URL is unset"))
        XCTAssertNotNil(script.range(of: "Complete real Supabase config, deployed schema migration, deployed Edge Functions including protected account functions, and an analyze sample image"))
        XCTAssertNotNil(script.range(of: "ALLOW_MISSING_BACKEND=1"))
        XCTAssertNil(script.range(of: "SUPABASE_ANON_KEY="))
    }

    func testSupabaseFunctionDenoCheckScriptCoversEveryEdgeFunction() throws {
        let scriptURL = projectURL("Scripts/check_supabase_functions.sh")
        let script = try String(contentsOf: scriptURL, encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(script.range(of: "DENO_BIN"))
        XCTAssertNotNil(script.range(of: "command -v deno"))
        XCTAssertNotNil(script.range(of: "npx --yes deno"))
        XCTAssertNotNil(script.range(of: "DENO_DIR"))
        XCTAssertNotNil(script.range(of: "deno-cache"))
        XCTAssertNotNil(script.range(of: "deno or npx is required"))
        XCTAssertNotNil(script.range(of: "deno_cmd"))
        XCTAssertNotNil(script.range(of: "check"))
        XCTAssertNotNil(script.range(of: "supabase/functions/analyze-image/index.ts"))
        XCTAssertNotNil(script.range(of: "supabase/functions/generate-listing/index.ts"))
        XCTAssertNotNil(script.range(of: "supabase/functions/store-apple-token/index.ts"))
        XCTAssertNotNil(script.range(of: "supabase/functions/delete-account/index.ts"))
        XCTAssertNotNil(script.range(of: "Supabase function Deno check passed"))
        XCTAssertNotNil(script.range(of: "functions: analyze-image generate-listing store-apple-token delete-account"))
    }

    func testSupabaseSchemaStaticCheckScriptCoversRLSGrantsIndexesAndSwiftParity() throws {
        let scriptURL = projectURL("Scripts/check_supabase_schema.sh")
        let script = try String(contentsOf: scriptURL, encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(script.range(of: "20260717000100_create_remote_history_and_apple_auth_tokens.sql"))
        XCTAssertNotNil(script.range(of: "20260718000100_harden_history_constraints.sql"))
        XCTAssertNotNil(script.range(of: "20260718000200_harden_apple_auth_token_identity.sql"))
        XCTAssertNotNil(script.range(of: "BuySellAI/Data/Marketplace.swift"))
        XCTAssertNotNil(script.range(of: "BuySellAI/Data/Models.swift"))
        XCTAssertNotNil(script.range(of: "Postgres does not support ADD CONSTRAINT IF NOT EXISTS"))
        XCTAssertNotNil(script.range(of: "alter\\s+table\\s+public\\.{table}\\s+enable\\s+row\\s+level\\s+security"))
        XCTAssertNotNil(script.range(of: "alter\\s+table\\s+public\\.{table}\\s+force\\s+row\\s+level\\s+security"))
        XCTAssertNotNil(script.range(of: "select\\s+auth\\.uid\\(\\)"))
        XCTAssertNotNil(script.range(of: "history_user_created_at_idx"))
        XCTAssertNotNil(script.range(of: "apple_auth_tokens_apple_user_id_unique"))
        XCTAssertNotNil(script.range(of: "revoke all on table public.history from anon"))
        XCTAssertNotNil(script.range(of: "grant select, insert, update, delete on table public.history to authenticated"))
        XCTAssertNotNil(script.range(of: "revoke all on table public.apple_auth_tokens from authenticated"))
        XCTAssertNotNil(script.range(of: "apple_auth_tokens must not grant authenticated table access"))
        XCTAssertNotNil(script.range(of: "require_value_parity(\"category\""))
        XCTAssertNotNil(script.range(of: "require_value_parity(\"condition\""))
        XCTAssertNotNil(script.range(of: "require_value_parity(\"marketplace\""))
        XCTAssertNotNil(script.range(of: "Supabase schema static check passed"))
        XCTAssertNotNil(script.range(of: "tables: history apple_auth_tokens"))
        XCTAssertNotNil(script.range(of: "rls: history apple_auth_tokens forced"))
        XCTAssertNotNil(script.range(of: "policy: history authenticated select-auth-uid"))
        XCTAssertNotNil(script.range(of: "indexes: history_user_created_at_idx apple_auth_tokens_apple_user_id_unique"))
        XCTAssertNotNil(script.range(of: "grants: history authenticated service_role apple_auth_tokens service_role"))
        XCTAssertNotNil(script.range(of: "constraints: history category condition marketplace listing apple-token-identity"))
        XCTAssertNotNil(script.range(of: "swift parity: category condition marketplace"))
    }

    func testSupabaseDeployHelperGuardsRemoteSchemaAndFunctionDeployment() throws {
        let scriptURL = projectURL("Scripts/deploy_supabase_backend.sh")
        let script = try String(contentsOf: scriptURL, encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(script.range(of: "ALLOW_MISSING_SUPABASE_DEPLOY"))
        XCTAssertNotNil(script.range(of: "M10 Supabase deploy preflight pending"))
        XCTAssertNotNil(script.range(of: "CONFIRM_SUPABASE_DEPLOY"))
        XCTAssertNotNil(script.range(of: "Supabase CLI is required; install it, run supabase login, and link the project"))
        XCTAssertNotNil(script.range(of: "supabase/.temp/project-ref"))
        XCTAssertNotNil(script.range(of: "Scripts/setup_supabase_config.sh"))
        XCTAssertNotNil(script.range(of: "Scripts/setup_supabase_secrets.sh full"))
        XCTAssertNotNil(script.range(of: "bash \"$repo_root/Scripts/check_supabase_schema.sh\""))
        XCTAssertNotNil(script.range(of: "bash \"$repo_root/Scripts/check_supabase_functions.sh\""))
        XCTAssertNotNil(script.range(of: "supabase/migrations/20260718000100_harden_history_constraints.sql"))
        XCTAssertNotNil(script.range(of: "supabase/migrations/20260718000200_harden_apple_auth_token_identity.sql"))
        XCTAssertNotNil(script.range(of: "supabase secrets list --project-ref \"$project_ref\" --output json"))
        XCTAssertNotNil(script.range(of: "supabase db push --linked --yes"))
        XCTAssertNotNil(script.range(of: "supabase functions deploy \"$function_name\" --project-ref \"$project_ref\" --use-api"))
        XCTAssertNotNil(script.range(of: "M10 Supabase deploy passed"))
        XCTAssertNotNil(script.range(of: "M10 Supabase deploy preflight passed"))
        XCTAssertNotNil(script.range(of: "schema: history apple_auth_tokens"))
        XCTAssertNotNil(script.range(of: "constraints: history category condition marketplace listing apple-token-identity"))
        XCTAssertNotNil(script.range(of: "functions: %s"))
        XCTAssertNotNil(script.range(of: "secrets: required names present"))

        for value in [
            "GEMINI_API_KEY",
            "SUPABASE_SERVICE_ROLE_KEY",
            "APPLE_TEAM_ID",
            "APPLE_KEY_ID",
            "APPLE_CLIENT_ID",
            "APPLE_PRIVATE_KEY",
            "analyze-image",
            "generate-listing",
            "store-apple-token",
            "delete-account"
        ] {
            XCTAssertNotNil(script.range(of: value))
        }

        XCTAssertNil(script.range(of: "supabase secrets set"))
        XCTAssertNil(script.range(of: "GEMINI_API_KEY="))
        XCTAssertNil(script.range(of: "SUPABASE_SERVICE_ROLE_KEY="))
        XCTAssertNil(script.range(of: "APPLE_PRIVATE_KEY="))
    }

    func testSupabaseSecretSetupScriptKeepsProviderSecretsOutOfSourceAndAppConfig() throws {
        let scriptURL = projectURL("Scripts/setup_supabase_secrets.sh")
        let script = try String(contentsOf: scriptURL, encoding: .utf8)
        let readme = try String(contentsOf: projectURL("README.md"), encoding: .utf8)
        let backendReadme = try String(contentsOf: projectURL("supabase/README.md"), encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(script.range(of: "mktemp \"${TMPDIR:-/tmp}/buysell-supabase-secrets.XXXXXX\""))
        XCTAssertNotNil(script.range(of: "chmod 600 \"$secret_file\""))
        XCTAssertNotNil(script.range(of: "trap cleanup EXIT"))
        XCTAssertNotNil(script.range(of: "SUPABASE_SECRETS_FROM_ENV"))
        XCTAssertNotNil(script.range(of: "SUPABASE_PROJECT_REF"))
        XCTAssertNotNil(script.range(of: "resolve_project_ref"))
        XCTAssertNotNil(script.range(of: "preflight"))
        XCTAssertNotNil(script.range(of: "require_secret_access"))
        XCTAssertNotNil(script.range(of: "supabase secrets list --project-ref \"$project_ref\" --output json >/dev/null"))
        XCTAssertNotNil(script.range(of: "before entering secrets"))
        XCTAssertNotNil(script.range(of: "Supabase secret setup preflight passed"))
        XCTAssertNotNil(script.range(of: "BuySellAI/App/Config.plist"))
        XCTAssertNotNil(script.range(of: "supabase/.temp/project-ref"))
        XCTAssertNotNil(script.range(of: "SUPABASE_PROJECT_REF is required"))
        XCTAssertNotNil(script.range(of: "read_secret_or_env \"Gemini API key: \" GEMINI_API_KEY"))
        XCTAssertNotNil(script.range(of: "read_secret_or_env \"Supabase service-role key: \" SUPABASE_SERVICE_ROLE_KEY"))
        XCTAssertNotNil(script.range(of: "read_required_or_env \"Apple Team ID: \" APPLE_TEAM_ID"))
        XCTAssertNotNil(script.range(of: "read_required_or_env \"Apple private key .p8 path: \" APPLE_PRIVATE_KEY_PATH"))
        XCTAssertNotNil(script.range(of: "validate_apple_private_key_path"))
        XCTAssertNotNil(script.range(of: "APPLE_PRIVATE_KEY_PATH must point to a .p8 file outside the repository"))
        XCTAssertNotNil(script.range(of: "APPLE_PRIVATE_KEY_PATH must not point inside the repository"))
        XCTAssertNotNil(script.range(of: "APPLE_PRIVATE_KEY_PATH must point to a .p8 private-key file"))
        XCTAssertNotNil(script.range(of: "BEGIN PRIVATE KEY"))
        XCTAssertNotNil(script.range(of: "is required in environment when SUPABASE_SECRETS_FROM_ENV=1"))
        XCTAssertNotNil(script.range(of: "write_secret \"GEMINI_API_KEY\" \"$GEMINI_API_KEY\""))
        XCTAssertNotNil(script.range(of: "write_secret \"APPLE_PRIVATE_KEY\" \"$APPLE_PRIVATE_KEY\""))
        XCTAssertNotNil(script.range(of: "supabase secrets set --project-ref \"$project_ref\" --env-file \"$secret_file\""))
        XCTAssertNotNil(script.range(of: "project ref: %s"))
        XCTAssertNotNil(script.range(of: "gemini-only"))
        XCTAssertNotNil(script.range(of: "temporary secret file must not be inside the repository"))
        XCTAssertNotNil(script.range(of: "Never put"))
        XCTAssertNotNil(script.range(of: "Gemini, service-role, or Apple private-key material"))
        XCTAssertNil(script.range(of: "> .env"))
        XCTAssertNil(script.range(of: "GEMINI_API_KEY="))
        XCTAssertNil(script.range(of: "SUPABASE_SERVICE_ROLE_KEY="))

        for text in [readme, backendReadme] {
            XCTAssertNotNil(text.range(of: "Scripts/setup_supabase_secrets.sh preflight"))
            XCTAssertNotNil(text.range(of: "Scripts/setup_supabase_secrets.sh full"))
            XCTAssertNotNil(text.range(of: "0600 temporary env file outside the repository"))
            XCTAssertNotNil(text.range(of: "before any secret values are requested"))
            XCTAssertNotNil(text.range(of: "SUPABASE_SECRETS_FROM_ENV"))
            XCTAssertNotNil(text.range(of: "SUPABASE_PROJECT_REF"))
            XCTAssertNotNil(text.range(of: "supabase secrets set --project-ref <project-ref> --env-file"))
            XCTAssertNotNil(text.range(of: "outside the repository and must be a `.p8` private-key file"))
            XCTAssertNotNil(text.range(of: "CI secret environment variables"))
            XCTAssertNotNil(text.range(of: "gemini-only"))
            XCTAssertNotNil(text.range(of: "full App Store readiness still requires"))
        }
    }

    func testSupabaseAppConfigSetupScriptFeedsBackendPreflightWithoutProviderSecrets() throws {
        let scriptURL = projectURL("Scripts/setup_supabase_config.sh")
        let script = try String(contentsOf: scriptURL, encoding: .utf8)
        let readme = try String(contentsOf: projectURL("README.md"), encoding: .utf8)
        let m10 = try String(contentsOf: projectURL("M10_ACCEPTANCE.md"), encoding: .utf8)
        let backendReadme = try String(contentsOf: projectURL("supabase/README.md"), encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(script.range(of: "CONFIG_PATH"))
        XCTAssertNotNil(script.range(of: "SUPABASE_CONFIG_FROM_ENV"))
        XCTAssertNotNil(script.range(of: "read_required_or_env \"Supabase project URL: \" supabase_url SUPABASE_URL"))
        XCTAssertNotNil(script.range(of: "read_required_or_env \"Supabase anon key: \" anon_key SUPABASE_ANON_KEY"))
        XCTAssertNotNil(script.range(of: "is required in environment when SUPABASE_CONFIG_FROM_ENV=1"))
        XCTAssertNotNil(script.range(of: "SUPABASE_URL must be a root https://<project>.supabase.co URL"))
        XCTAssertNotNil(script.range(of: "SUPABASE_URL still contains the Config.plist.example placeholder"))
        XCTAssertNotNil(script.range(of: "SUPABASE_ANON_KEY still contains the Config.plist.example placeholder"))
        XCTAssertNotNil(script.range(of: "SUPABASE_ANON_KEY looks like a provider-secret-shaped value"))
        XCTAssertNotNil(script.range(of: "keys: SUPABASE_URL SUPABASE_ANON_KEY"))
        XCTAssertNil(script.range(of: "printf 'SUPABASE_ANON_KEY"))

        for text in [readme, m10, backendReadme] {
            XCTAssertNotNil(text.range(of: "Scripts/setup_supabase_config.sh"))
            XCTAssertNotNil(text.range(of: "BuySellAI/App/Config.plist"))
            XCTAssertNotNil(text.range(of: "provider-secret-shaped values"))
        }
        XCTAssertNotNil(readme.range(of: "reads them from environment variables with the same names for noninteractive setup"))
        XCTAssertNotNil(readme.range(of: "SUPABASE_CONFIG_FROM_ENV"))
        XCTAssertNotNil(m10.range(of: "reads environment variables with the same names for noninteractive setup"))
        XCTAssertNotNil(m10.range(of: "SUPABASE_CONFIG_FROM_ENV=1"))
        XCTAssertNotNil(backendReadme.range(of: "reads environment variables with the same names for noninteractive setup"))
        XCTAssertNotNil(backendReadme.range(of: "SUPABASE_CONFIG_FROM_ENV=1"))
    }

    func testCombinedSubmitReadinessRequiresBackendPreflightLogAndDocsRouteThroughGate() throws {
        let script = try String(contentsOf: projectURL("Scripts/verify_m10_submit_readiness.sh"), encoding: .utf8)
        let readme = try String(contentsOf: projectURL("README.md"), encoding: .utf8)
        let m10 = try String(contentsOf: projectURL("M10_ACCEPTANCE.md"), encoding: .utf8)

        XCTAssertNotNil(script.range(of: "M10_BACKEND_LOG"))
        XCTAssertNotNil(script.range(of: "/tmp/buysell-submit-readiness-backend.log"))
        XCTAssertNotNil(script.range(of: "M10 backend preflight passed"))
        XCTAssertNotNil(script.range(of: "schema: history apple_auth_tokens"))
        XCTAssertNotNil(script.range(of: "functions: analyze-image generate-listing store-apple-token delete-account"))
        XCTAssertNotNil(script.range(of: "protected functions: store-apple-token delete-account"))
        XCTAssertNotNil(script.range(of: "protected tables: history apple_auth_tokens"))
        XCTAssertNotNil(script.range(of: "analyze rejection contract: missing jpeg base64"))
        XCTAssertNotNil(script.range(of: "listing contract: title-description-plain-text"))
        XCTAssertNotNil(script.range(of: "listing rejection contract: platform category condition"))
        XCTAssertNotNil(script.range(of: "backend preflight log"))
        XCTAssertNotNil(script.range(of: "M10BackendPreflightScriptTests/testBackendPreflightScriptValidatesConfigAndCallsRequiredSupabaseRoutes"))

        XCTAssertNotNil(readme.range(of: "Scripts/preflight_m10_backend.sh"))
        XCTAssertNotNil(readme.range(of: "Scripts/setup_supabase_config.sh"))
        XCTAssertNotNil(readme.range(of: "Scripts/check_supabase_functions.sh"))
        XCTAssertNotNil(readme.range(of: "/tmp/buysell-submit-readiness-supabase-functions.log"))
        XCTAssertNotNil(readme.range(of: "ALLOW_MISSING_BACKEND=1"))
        XCTAssertNotNil(readme.range(of: "/tmp/buysell-submit-readiness-backend.log"))
        XCTAssertNotNil(m10.range(of: "Scripts/preflight_m10_backend.sh"))
        XCTAssertNotNil(m10.range(of: "Scripts/setup_supabase_config.sh"))
        XCTAssertNotNil(m10.range(of: "Scripts/check_supabase_functions.sh"))
        XCTAssertNotNil(m10.range(of: "Scripts/setup_supabase_secrets.sh full"))
        XCTAssertNotNil(m10.range(of: "/tmp/buysell-submit-readiness-supabase-functions.log"))
        XCTAssertNotNil(m10.range(of: "Run the M10 backend smoke preflight"))
        XCTAssertNotNil(m10.range(of: "/tmp/buysell-submit-readiness-backend.log"))
    }

    private func projectURL(_ path: String) -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent(path)
    }
}
