import Foundation
import XCTest

final class M10SubmitReadinessScriptTests: XCTestCase {
    func testSubmitReadinessScriptAggregatesAllM10EvidenceGates() throws {
        let scriptURL = projectURL("Scripts/verify_m10_submit_readiness.sh")
        let script = try String(contentsOf: scriptURL, encoding: .utf8)

        XCTAssertTrue(FileManager.default.fileExists(atPath: scriptURL.path))
        XCTAssertNotNil(script.range(of: "M10_FULL_XCRESULT"))
        XCTAssertNotNil(script.range(of: "M10_FOCUSED_XCRESULT"))
        XCTAssertNotNil(script.range(of: "M10_MIN_TESTS:-320"))
        XCTAssertNotNil(script.range(of: "M10_MIN_FOCUSED_TESTS:-60"))
        XCTAssertNotNil(script.range(of: "M10_SIGNED_ARCHIVE"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_ARCHIVE"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_EXPORT"))
        XCTAssertNotNil(script.range(of: "M10_APP_STORE_METADATA"))
        XCTAssertNotNil(script.range(of: "M10_BACKEND_LOG"))
        XCTAssertNotNil(script.range(of: "M10_INSTRUMENTS_EVIDENCE"))
        XCTAssertNotNil(script.range(of: "required_performance_tests"))
        XCTAssertNotNil(script.range(of: "xcrun xcresulttool get test-results summary"))
        XCTAssertNotNil(script.range(of: "require_xcresult_contains_tests"))
        XCTAssertNotNil(script.range(of: "require_same_marker_value"))
        XCTAssertNotNil(script.range(of: "require_metadata_references_marker_value"))
        XCTAssertNotNil(script.range(of: "require_metadata_matches_marker_value"))
        XCTAssertNotNil(script.range(of: "require_same_metadata_value"))
        XCTAssertNotNil(script.range(of: "require_fresh_artifact"))
        XCTAssertNotNil(script.range(of: "require_fresh_pass_log"))
        XCTAssertNotNil(script.range(of: "current HEAD commit"))
        XCTAssertNotNil(script.range(of: "markdown_metadata_value"))
        XCTAssertNotNil(script.range(of: "AppStoreValidationPreflightScriptTests/testAppStoreValidationPreflightChecksPrivacyManifestContents"))
        XCTAssertNotNil(script.range(of: "RealDevicePreflightScriptTests/testRealDeviceAcceptanceVerifierParsesTimingEvidenceInMillisecondsOrSeconds"))
        XCTAssertNotNil(script.range(of: "M10BackendPreflightScriptTests/testBackendPreflightScriptValidatesConfigAndCallsRequiredSupabaseRoutes"))
        XCTAssertNotNil(script.range(of: "M10AppStoreMetadataScriptTests/testMetadataVerifierRequiresConcreteAppStoreConnectSubmissionFields"))
        XCTAssertNotNil(script.range(of: "SigningCapabilityTests/testAppTargetBuildConfigurationsUseEntitlementsAndAutomaticSigning"))
        XCTAssertNotNil(script.range(of: "M10 local archive check passed"))
        XCTAssertNotNil(script.range(of: "M10 signed archive preflight passed"))
        XCTAssertNotNil(script.range(of: "M10 App Store export preflight passed"))
        XCTAssertNotNil(script.range(of: "M10 App Store validation preflight passed"))
        XCTAssertNotNil(script.range(of: "M10 App Store metadata evidence passed"))
        XCTAssertNotNil(script.range(of: "M10 backend preflight passed"))
        XCTAssertNotNil(script.range(of: "M10 real-device preflight passed"))
        XCTAssertNotNil(script.range(of: "M10 secret scan self-test passed"))
        XCTAssertNotNil(script.range(of: "M10 secret scan passed"))
        XCTAssertNotNil(script.range(of: "M10 Instruments evidence passed"))
        XCTAssertNotNil(script.range(of: "verify_m10_real_device_acceptance.sh"))
    }

    func testSubmitReadinessScriptRequiresConcreteLogArtifactMarkers() throws {
        let script = try String(contentsOf: projectURL("Scripts/verify_m10_submit_readiness.sh"), encoding: .utf8)

        XCTAssertNotNil(script.range(of: "require_directory \"$signed_archive\""))
        XCTAssertNotNil(script.range(of: "require_directory \"$app_store_archive\""))
        XCTAssertNotNil(script.range(of: "require_directory \"$app_store_export\""))
        XCTAssertNotNil(script.range(of: "full simulator suite result bundle"))
        XCTAssertNotNil(script.range(of: "focused M10 preflight result bundle"))
        XCTAssertNotNil(script.range(of: "no-sign Release archive"))
        XCTAssertNotNil(script.range(of: "is older than the current HEAD commit"))
        XCTAssertNotNil(script.range(of: #"return 0"#))
        XCTAssertNotNil(script.range(of: #"[[ ! -e "$path" ]]"#))
        XCTAssertNotNil(script.range(of: #"[[ ! -f "$file" ]]"#))
        XCTAssertNotNil(script.range(of: "archive: $no_sign_archive"))
        XCTAssertNotNil(script.range(of: "app icon:"))
        XCTAssertNotNil(script.range(of: "archive: $signed_archive"))
        XCTAssertNotNil(script.range(of: "archive: $app_store_archive"))
        XCTAssertNotNil(script.range(of: "export: $app_store_export"))
        XCTAssertNotNil(script.range(of: "ipa:"))
        XCTAssertNotNil(script.range(of: "bundle id: com.rhodes.buysellai"))
        XCTAssertNotNil(script.range(of: "signed bundle id"))
        XCTAssertNotNil(script.range(of: "exported bundle id"))
        XCTAssertNotNil(script.range(of: "validated bundle id"))
        XCTAssertNotNil(script.range(of: "real-device bundle id"))
        XCTAssertNotNil(script.range(of: "performance bundle id"))
        XCTAssertNotNil(script.range(of: "sign in with apple: Default"))
        XCTAssertNotNil(script.range(of: "Sign in with Apple entitlement"))
        XCTAssertNotNil(script.range(of: "validated Sign in with Apple entitlement"))
        XCTAssertNotNil(script.range(of: "real-device Sign in with Apple entitlement"))
        XCTAssertNotNil(script.range(of: "validated IPA"))
        XCTAssertNotNil(script.range(of: "release build:"))
        XCTAssertNotNil(script.range(of: "signed release build"))
        XCTAssertNotNil(script.range(of: "exported release build"))
        XCTAssertNotNil(script.range(of: "validated release build"))
        XCTAssertNotNil(script.range(of: "real-device release build"))
        XCTAssertNotNil(script.range(of: "performance release build"))
        XCTAssertNotNil(script.range(of: "mismatch"))
        XCTAssertNotNil(script.range(of: "signed archive metadata"))
        XCTAssertNotNil(script.range(of: "signed archive validation metadata"))
        XCTAssertNotNil(script.range(of: "App Store validation metadata"))
        XCTAssertNotNil(script.range(of: "acceptance release build metadata"))
        XCTAssertNotNil(script.range(of: "Instruments release build metadata"))
        XCTAssertNotNil(script.range(of: #"metadata '$metadata_field' must reference '$marker_path'"#))
        XCTAssertNotNil(script.range(of: #"metadata '$metadata_field' is '$metadata', $log_label has '$marker_text'"#))
        XCTAssertNotNil(script.range(of: #"$acceptance_file" "Signed archive" "$signed_log" "archive:"#))
        XCTAssertNotNil(script.range(of: #"$acceptance_file" "Signed archive validation" "$signed_log" "archive:"#))
        XCTAssertNotNil(script.range(of: #"$acceptance_file" "App Store validation" "$validation_log" "ipa:"#))
        XCTAssertNotNil(script.range(of: #"$acceptance_file" "Release build" "$signed_log" "release build:"#))
        XCTAssertNotNil(script.range(of: #"$no_sign_log" "bundle id:" "no-sign archive verifier log" "$signed_log" "bundle id:" "signed archive preflight log""#))
        XCTAssertNotNil(script.range(of: #"$signed_log" "bundle id:" "signed archive preflight log" "$export_log" "bundle id:" "App Store export preflight log""#))
        XCTAssertNotNil(script.range(of: #"$export_log" "bundle id:" "App Store export preflight log" "$validation_log" "bundle id:" "App Store validation preflight log""#))
        XCTAssertNotNil(script.range(of: #"$signed_log" "bundle id:" "signed archive preflight log" "$real_device_log" "bundle id:" "real-device preflight log""#))
        XCTAssertNotNil(script.range(of: #"$no_sign_log" "bundle id:" "no-sign archive verifier log" "$performance_log" "bundle id:" "performance evidence log""#))
        XCTAssertNotNil(script.range(of: #"$signed_log" "sign in with apple:" "signed archive preflight log" "$export_log" "sign in with apple:" "App Store export preflight log""#))
        XCTAssertNotNil(script.range(of: #"$export_log" "sign in with apple:" "App Store export preflight log" "$validation_log" "sign in with apple:" "App Store validation preflight log""#))
        XCTAssertNotNil(script.range(of: #"$signed_log" "sign in with apple:" "signed archive preflight log" "$real_device_log" "sign in with apple:" "real-device preflight log""#))
        XCTAssertNotNil(script.range(of: #"$no_sign_log" "release build:" "no-sign archive verifier log" "$signed_log" "release build:" "signed archive preflight log""#))
        XCTAssertNotNil(script.range(of: #"$signed_log" "release build:" "signed archive preflight log" "$real_device_log" "release build:" "real-device preflight log""#))
        XCTAssertNotNil(script.range(of: #"$no_sign_log" "release build:" "no-sign archive verifier log" "$performance_log" "release build:" "performance evidence log""#))
        XCTAssertNotNil(script.range(of: #"$acceptance_file" "Device model" "$real_device_log" "device name:"#))
        XCTAssertNotNil(script.range(of: #"$instruments_evidence" "Signed archive" "$signed_log" "archive:"#))
        XCTAssertNotNil(script.range(of: #"$instruments_evidence" "Device model" "$real_device_log" "device name:"#))
        XCTAssertNotNil(script.range(of: #"$instruments_evidence" "Release build" "$signed_log" "release build:"#))
        XCTAssertNotNil(script.range(of: #"$acceptance_file" "iOS version" "acceptance" "$instruments_evidence" "iOS version" "Instruments""#))
        XCTAssertNotNil(script.range(of: #"$acceptance_file" "Release build" "acceptance" "$instruments_evidence" "Release build" "Instruments""#))
        XCTAssertNotNil(script.range(of: "M10 physical-device iOS version"))
        XCTAssertNotNil(script.range(of: "M10 physical-device release build"))
        XCTAssertNotNil(script.range(of: "Instruments signed archive metadata"))
        XCTAssertNotNil(script.range(of: "acceptance device metadata"))
        XCTAssertNotNil(script.range(of: "Instruments device metadata"))
        XCTAssertNotNil(script.range(of: "device:"))
        XCTAssertNotNil(script.range(of: "device name:"))
        XCTAssertNotNil(script.range(of: "device id:"))
        XCTAssertNotNil(script.range(of: "app:"))
        XCTAssertNotNil(script.range(of: "full suite: $full_result"))
        XCTAssertNotNil(script.range(of: "archive log: $no_sign_log"))
        XCTAssertNotNil(script.range(of: #"$performance_log" "release build:" "performance evidence log"#))
        XCTAssertNotNil(script.range(of: "performance tests:"))
        XCTAssertNotNil(script.range(of: "performance test: $test_id"))
        XCTAssertNotNil(script.range(of: "app size:"))
        XCTAssertNotNil(script.range(of: "file: $instruments_evidence"))
        XCTAssertNotNil(script.range(of: "backend preflight log"))
        XCTAssertNotNil(script.range(of: "functions: analyze-image generate-listing"))
        XCTAssertNotNil(script.range(of: "analyze item:"))
        XCTAssertNotNil(script.range(of: "listing bytes:"))
        XCTAssertNotNil(script.range(of: "App Store metadata evidence log"))
        XCTAssertNotNil(script.range(of: "app privacy:"))
        XCTAssertNotNil(script.range(of: "legal:"))
        XCTAssertNotNil(script.range(of: "screenshots:"))
        XCTAssertNotNil(script.range(of: "screenshot directory:"))
        XCTAssertNotNil(script.range(of: "screenshot files: 4"))
        XCTAssertNotNil(script.range(of: "screenshot dimensions: 1206x2622"))
        XCTAssertNotNil(script.range(of: "screenshot result bundle:"))
        XCTAssertNotNil(script.range(of: "screenshot capture test: BuySellAIUITests/testM10AppStoreScreenshotsCanBeCaptured()"))
    }

    func testSubmitReadinessScriptRequiresFinalAcceptanceDocsToBeComplete() throws {
        let script = try String(contentsOf: projectURL("Scripts/verify_m10_submit_readiness.sh"), encoding: .utf8)

        XCTAssertNotNil(script.range(of: "require_submit_checkboxes"))
        XCTAssertNotNil(script.range(of: "Submit-Ready Gates"))
        XCTAssertNotNil(script.range(of: "unchecked Submit-Ready Gates"))
        XCTAssertNotNil(script.range(of: "require_result_log_final"))
        XCTAssertNotNil(script.range(of: "is_placeholder_value"))
        XCTAssertNotNil(script.range(of: "metadata_matched_rows"))
        XCTAssertNotNil(script.range(of: #"markdown_metadata_value "$acceptance_file" "Device model""#))
        XCTAssertNotNil(script.range(of: "Result Log row"))
        XCTAssertNotNil(script.range(of: "Result Log"))
        XCTAssertNotNil(script.range(of: "Result Log needs at least one completed Pass row"))
        XCTAssertNotNil(script.range(of: "Result Log has no completed Pass row"))
        XCTAssertNotNil(script.range(of: "Result Log needs a Pass row matching recorded Date, Tester, Device model, iOS version, and Backend project metadata"))
        XCTAssertNotNil(script.range(of: "Result Log still has pending rows"))
        XCTAssertNotNil(script.range(of: "Notes must mention final evidence"))
        XCTAssertNotNil(script.range(of: "signed archive"))
        XCTAssertNotNil(script.range(of: "Xcode Organizer signed archive validation"))
        XCTAssertNotNil(script.range(of: #"archive validation"#))
        XCTAssertNotNil(script.range(of: "App Store validation"))
        XCTAssertNotNil(script.range(of: "real-device acceptance"))
        XCTAssertNotNil(script.range(of: "Instruments evidence"))
        XCTAssertNotNil(script.range(of: "expected Pass"))
    }

    func testSubmitReadinessScriptHasPendingModeForExternalBlockers() throws {
        let script = try String(contentsOf: projectURL("Scripts/verify_m10_submit_readiness.sh"), encoding: .utf8)

        XCTAssertNotNil(script.range(of: "ALLOW_PENDING_M10"))
        XCTAssertNotNil(script.range(of: "M10 submit readiness pending"))
        XCTAssertNotNil(script.range(of: "M10 submit readiness incomplete"))
        XCTAssertNotNil(script.range(of: "M10 submit readiness passed"))
        XCTAssertNotNil(script.range(of: "Complete every signed archive, App Store, backend, real-device, and evidence item"))
    }

    func testAcceptanceDocsAndReadmeRouteThroughCombinedSubmitReadinessGate() throws {
        let readme = try String(contentsOf: projectURL("README.md"), encoding: .utf8)
        let m10 = try String(contentsOf: projectURL("M10_ACCEPTANCE.md"), encoding: .utf8)

        XCTAssertNotNil(readme.range(of: "Scripts/verify_m10_submit_readiness.sh M10_ACCEPTANCE.md"))
        XCTAssertNotNil(readme.range(of: "ALLOW_PENDING_M10=1"))
        XCTAssertNotNil(m10.range(of: "Scripts/verify_m10_submit_readiness.sh M10_ACCEPTANCE.md"))
        XCTAssertNotNil(m10.range(of: "ALLOW_PENDING_M10=1"))
        XCTAssertNotNil(m10.range(of: "Run the combined M10 submit-readiness gate without `ALLOW_PENDING_M10=1`"))
        XCTAssertNotNil(m10.range(of: "/tmp/buysell-submit-readiness-full.xcresult"))
        XCTAssertNotNil(m10.range(of: "/tmp/buysell-submit-readiness-app-store-metadata.log"))
        XCTAssertNotNil(m10.range(of: "/tmp/buysell-submit-readiness-backend.log"))
        XCTAssertNotNil(m10.range(of: "/tmp/buysell-submit-readiness-instruments.log"))
        XCTAssertNotNil(m10.range(of: "/tmp/buysell-submit-readiness-combined.log"))
        XCTAssertNotNil(readme.range(of: "The final `Result Log` must include a complete `Pass` row"))
        XCTAssertNotNil(readme.range(of: "At least one Pass row must match the recorded Date, Tester, Device model, iOS version, and Backend project metadata"))
        XCTAssertNotNil(readme.range(of: "The combined gate expects retained artifact markers"))
        XCTAssertNotNil(readme.range(of: "current HEAD commit"))
        XCTAssertNotNil(readme.range(of: "same `ipa:` path produced by the export preflight"))
        XCTAssertNotNil(readme.range(of: "logs retain the same `bundle id:` marker"))
        XCTAssertNotNil(readme.range(of: "logs retain the same `sign in with apple:` entitlement marker"))
        XCTAssertNotNil(readme.range(of: "performance evidence log retains the same no-sign archive `bundle id:` and `release build:` values"))
        XCTAssertNotNil(readme.range(of: "backend preflight log proves the live `analyze-image` and `generate-listing` Edge Functions"))
        XCTAssertNotNil(readme.range(of: "screenshot dimensions:"))
        XCTAssertNotNil(readme.range(of: "manual acceptance and Instruments metadata reference the real-device preflight `device name:` value"))
        XCTAssertNotNil(readme.range(of: "signed archive validation proof from Xcode Organizer"))
        XCTAssertNotNil(readme.range(of: "matching iOS version and release build metadata"))
        XCTAssertNotNil(readme.range(of: "release build must match the signed-preflight `release build:` marker"))
        XCTAssertNotNil(readme.range(of: "M10_SIGNED_ARCHIVE"))
        XCTAssertNotNil(readme.range(of: "M10_APP_STORE_EXPORT"))
        XCTAssertNotNil(readme.range(of: "M10_APP_STORE_METADATA"))
        XCTAssertNotNil(readme.range(of: "M10_BACKEND_LOG"))
        XCTAssertNotNil(m10.range(of: "pass logs retain their concrete artifact markers"))
        XCTAssertNotNil(m10.range(of: "current HEAD commit"))
        XCTAssertNotNil(m10.range(of: "same `ipa:` path produced by the export preflight"))
        XCTAssertNotNil(m10.range(of: "logs retain the same `bundle id:` marker"))
        XCTAssertNotNil(m10.range(of: "logs retain the same `sign in with apple:` entitlement marker"))
        XCTAssertNotNil(m10.range(of: "performance evidence log retains the same no-sign archive `bundle id:` and `release build:` values"))
        XCTAssertNotNil(m10.range(of: "App Store metadata `app name:`, `bundle id:`, `privacy policy:`, `support:`, `screenshots:`, `legal:`, `screenshot directory:`, `screenshot files:`, `screenshot dimensions:`, `screenshot result bundle:`, `screenshot capture test:`, and `app privacy:`"))
        XCTAssertNotNil(m10.range(of: "screenshot dimensions:"))
        XCTAssertNotNil(m10.range(of: "backend `config:`, `project:`, `functions:`, `analyze item:`, and `listing bytes:`"))
        XCTAssertNotNil(m10.range(of: "real-device `device:`, `device name:`, `device id:`, `app:`, `bundle id:`, `sign in with apple:`, and `release build:`"))
        XCTAssertNotNil(m10.range(of: "acceptance `Signed archive` metadata references the signed-preflight `archive:` path"))
        XCTAssertNotNil(m10.range(of: "acceptance `Signed archive validation` metadata mentions Xcode Organizer validation proof"))
        XCTAssertNotNil(m10.range(of: "acceptance `App Store validation` metadata references the validated `ipa:` path"))
        XCTAssertNotNil(m10.range(of: "acceptance and Instruments `Release build` metadata match the signed-preflight `release build:` value"))
        XCTAssertNotNil(m10.range(of: "acceptance and Instruments `Device model` metadata reference the real-device preflight `device name:` value"))
        XCTAssertNotNil(m10.range(of: "Instruments `Signed archive` metadata references the same signed-preflight `archive:` path"))
        XCTAssertNotNil(m10.range(of: "acceptance and Instruments `iOS version` and `Release build` metadata match"))
        XCTAssertNotNil(m10.range(of: "real-device `device:`"))
        XCTAssertNotNil(m10.range(of: "Instruments `file:`"))
        XCTAssertNotNil(m10.range(of: "Every field must be concrete"))
        XCTAssertNotNil(m10.range(of: "`Result` must be `Pass`"))
        XCTAssertNotNil(m10.range(of: "the row must match the recorded Date, Tester, Device model, iOS version, and Backend project metadata"))
        XCTAssertNotNil(readme.range(of: "The Notes field must mention the signed archive, Xcode Organizer signed archive validation, App Store validation, real-device acceptance, and Instruments evidence"))
        XCTAssertNotNil(m10.range(of: "`Notes` must mention the signed archive, Xcode Organizer signed archive validation, App Store validation, real-device acceptance, and Instruments evidence"))
    }

    private func projectURL(_ path: String) -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent(path)
    }
}
